# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-01-07 08:36+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: authentication/user/views.py:24
msgid "User created succesfully"
msgstr "Profilo utente creato con successo"

#: authentication/user/views.py:27
msgid "Error while creating user"
msgstr "Errore durante la creazione del profilo utente"

#: authentication/user/views.py:48
msgid "Error during login"
msgstr "Errore durante l'accesso al sistema"

#: authentication/user/views.py:64
msgid "Password changed succesfully"
msgstr "Modifica password effettuata con successo"

#: authentication/user/views.py:66
msgid "Error during password change"
msgstr "Errore durante la modifica delle credenziali di accesso"

#: customer/views.py:47
msgid "Customer already exists"
msgstr "Cliente già presente"

#: customer/views.py:56 customer/views.py:74 customer/views.py:114
#: customer/views.py:132 repair/views.py:64 repair/views.py:78
#: warehouse/article/views.py:44 warehouse/article/views.py:57
msgid "Error while parsing request"
msgstr "Errore durante l'elaborazione della richiesta"

#: customer/views.py:60
msgid ""
"Error while creating user. Fidelity card is already assigned to another user"
msgstr ""
"Errore durante la creazione del cliente. Tessera fedeltà già assegnata ad un "
"altro cliente"

#: customer/views.py:71 customer/views.py:95
msgid "Customer not found"
msgstr "Cliente non trovato"

#: customer/views.py:78
msgid ""
"Error while updating user. Fidelity card is already assigned to another user"
msgstr ""
"Errore durante l'aggiornamento del cliente. Tessera fedeltà già assegnata ad "
"un altro cliente"

#: customer/views.py:85
msgid "Customer deleted successfully"
msgstr "Cliente eliminato con successo"

#: customer/views.py:87
msgid "Unable to delete. Customer not found"
msgstr "Impossibile eliminare il cliente selezionato. Il cliente non esiste"

#: customer/views.py:105
msgid "Fidelity card already exists"
msgstr "Tessera fedeltà già presente"

#: customer/views.py:118
msgid ""
"Error while creating fidelity card. Fidelity card is already assigned to "
"another user"
msgstr ""
"Errore durante la creazione della tessera fedeltà. Tessera fedeltà già "
"assegnata ad un altro cliente"

#: customer/views.py:129 customer/views.py:144
msgid "Fidelity card not found"
msgstr "Tessera fedeltà non trovata"

#: customer/views.py:136
msgid ""
"Error while updating fidelity card. Fidelity card is already assigned to "
"another user"
msgstr ""
"Errore durante l'aggiornamento della tessera fedeltà. Tessera fedeltà già "
"assegnata ad un altro cliente"

#: repair/views.py:49
msgid "Repair not found"
msgstr "Riparazione non trovata"

#: repair/views.py:54
msgid "Repair already exists"
msgstr "Riparazione già presente"

#: repair/views.py:75
msgid "Unable to edit. Repair not found"
msgstr ""
"Impossibile modificare la riparazione selezionata. La riparazione non esiste"

#: repair/views.py:86
msgid "Unable to delete. Repair not found"
msgstr ""
"Impossibile eliminare la riparazione selezionata. La riparazione non esiste"

#: repair/views.py:99
msgid "Unable to print receipt. Repair not found"
msgstr "Impossibile stampare la ricevuta. La riparazione non esiste"

#: repair/views.py:102
msgid "Receipt printer not available"
msgstr "Stampante ricevute non disponibile"

#: repair/views.py:105
msgid "Error while printing receipt"
msgstr "Errore durante la stampa della ricevuta"

#: repair/views.py:107
msgid "Receipt printed successfully"
msgstr "Ricevuta stampata con successo"

#: repair/views.py:119
msgid "Unable to print label. Repair not found"
msgstr "Impossibile stampare l'etichetta. La riparazione non esiste"

#: repair/views.py:122 warehouse/article/views.py:83
msgid "Label printer not available"
msgstr "Stampante etichette non disponibile"

#: repair/views.py:125 warehouse/article/views.py:86
msgid "Error while printing label"
msgstr "Errore durante la stampa dell'etichetta"

#: repair/views.py:127 warehouse/article/views.py:88
msgid "Label printed successfully"
msgstr "Etichetta stampata con successo"

#: venv/lib/python3.8/site-packages/argcomplete/my_argparse.py:127
#: venv/lib/python3.8/site-packages/argparse.py:1821
#, python-format
msgid "not allowed with argument %s"
msgstr ""

#: venv/lib/python3.8/site-packages/argcomplete/my_argparse.py:186
#: venv/lib/python3.8/site-packages/argcomplete/my_argparse.py:200
#: venv/lib/python3.8/site-packages/argparse.py:1867
#: venv/lib/python3.8/site-packages/argparse.py:1881
#, python-format
msgid "ignored explicit argument %r"
msgstr ""

#: venv/lib/python3.8/site-packages/argcomplete/my_argparse.py:306
#: venv/lib/python3.8/site-packages/argparse.py:1971
msgid "too few arguments"
msgstr ""

#: venv/lib/python3.8/site-packages/argcomplete/my_argparse.py:313
#: venv/lib/python3.8/site-packages/argparse.py:1978
#, python-format
msgid "argument %s is required"
msgstr ""

#: venv/lib/python3.8/site-packages/argcomplete/my_argparse.py:327
#: venv/lib/python3.8/site-packages/argparse.py:2003
#, python-format
msgid "one of the arguments %s is required"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:319
msgid "usage: "
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:827
msgid ".__call__() not defined"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1122
#, python-format
msgid "unknown parser %r (choices: %s)"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1163
#, python-format
msgid "argument \"-\" with mode %r"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1174
#, python-format
msgid "can't open '%s': %s"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1371
#, python-format
msgid "cannot merge actions - two groups are named %r"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1409
msgid "'required' is an invalid argument for positionals"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1429
#, python-format
msgid "invalid option string %r: must start with a character %r"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1450
#, python-format
msgid "dest= is required for options like %r"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1467
#, python-format
msgid "invalid conflict_resolution value: %r"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1485
#, python-format
msgid "conflicting option string(s): %s"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1548
msgid "mutually exclusive arguments must be optional"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1618
msgid "positional arguments"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1619
msgid "optional arguments"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1637
msgid "show this help message and exit"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1643
msgid "show program's version number and exit"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1675
msgid "cannot have multiple subparser arguments"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:1727
#, python-format
msgid "unrecognized arguments: %s"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:2049
msgid "expected one argument"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:2050
msgid "expected at most one argument"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:2051
msgid "expected at least one argument"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:2053
#, python-format
msgid "expected %s argument(s)"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:2110
#, python-format
msgid "ambiguous option: %s could match %s"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:2172
#, python-format
msgid "unexpected option string: %s"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:2273
#, python-format
msgid "%r is not callable"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:2289
#, python-format
msgid "invalid %s value: %r"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:2299
#, python-format
msgid "invalid choice: %r (choose from %s)"
msgstr ""

#: venv/lib/python3.8/site-packages/argparse.py:2392
#, python-format
msgid "%s: error: %s\n"
msgstr ""

#: venv/lib/python3.8/site-packages/click/_termui_impl.py:496
#, python-brace-format
msgid "{editor}: Editing failed"
msgstr ""

#: venv/lib/python3.8/site-packages/click/_termui_impl.py:500
#, python-brace-format
msgid "{editor}: Editing failed: {e}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:1097
msgid "Aborted!"
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:1282
#: venv/lib/python3.8/site-packages/click/decorators.py:495
msgid "Show this message and exit."
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:1313
#: venv/lib/python3.8/site-packages/click/core.py:1339
#, python-brace-format
msgid "(Deprecated) {text}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:1357
msgid "Options"
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:1383
#, python-brace-format
msgid "Got unexpected extra argument ({args})"
msgid_plural "Got unexpected extra arguments ({args})"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/click/core.py:1399
msgid "DeprecationWarning: The command {name!r} is deprecated."
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:1605
msgid "Commands"
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:1637
msgid "Missing command."
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:1715
msgid "No such command {name!r}."
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:2271
msgid "Value must be an iterable."
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:2291
#, python-brace-format
msgid "Takes {nargs} values but 1 was given."
msgid_plural "Takes {nargs} values but {len} were given."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/click/core.py:2734
#, python-brace-format
msgid "env var: {var}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:2764
msgid "(dynamic)"
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:2777
#, python-brace-format
msgid "default: {default}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/core.py:2790
msgid "required"
msgstr ""

#: venv/lib/python3.8/site-packages/click/decorators.py:400
#, python-format
msgid "%(prog)s, version %(version)s"
msgstr ""

#: venv/lib/python3.8/site-packages/click/decorators.py:464
msgid "Show the version and exit."
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:43
#: venv/lib/python3.8/site-packages/click/exceptions.py:79
#, python-brace-format
msgid "Error: {message}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:71
#, python-brace-format
msgid "Try '{command} {option}' for help."
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:120
#, python-brace-format
msgid "Invalid value: {message}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:122
#, python-brace-format
msgid "Invalid value for {param_hint}: {message}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:178
msgid "Missing argument"
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:180
msgid "Missing option"
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:182
msgid "Missing parameter"
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:184
#, python-brace-format
msgid "Missing {param_type}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:191
#, python-brace-format
msgid "Missing parameter: {param_name}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:211
#, python-brace-format
msgid "No such option: {name}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:223
#, python-brace-format
msgid "Did you mean {possibility}?"
msgid_plural "(Possible options: {possibilities})"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:261
msgid "unknown error"
msgstr ""

#: venv/lib/python3.8/site-packages/click/exceptions.py:268
msgid "Could not open file {filename!r}: {message}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/parser.py:231
msgid "Argument {name!r} takes {nargs} values."
msgstr ""

#: venv/lib/python3.8/site-packages/click/parser.py:413
msgid "Option {name!r} does not take a value."
msgstr ""

#: venv/lib/python3.8/site-packages/click/parser.py:474
msgid "Option {name!r} requires an argument."
msgid_plural "Option {name!r} requires {nargs} arguments."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/click/shell_completion.py:316
msgid "Shell completion is not supported for Bash versions older than 4.4."
msgstr ""

#: venv/lib/python3.8/site-packages/click/shell_completion.py:322
msgid "Couldn't detect Bash version, shell completion is not supported."
msgstr ""

#: venv/lib/python3.8/site-packages/click/termui.py:160
msgid "Repeat for confirmation"
msgstr ""

#: venv/lib/python3.8/site-packages/click/termui.py:176
msgid "Error: The value you entered was invalid."
msgstr ""

#: venv/lib/python3.8/site-packages/click/termui.py:178
#, python-brace-format
msgid "Error: {e.message}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/termui.py:189
msgid "Error: The two entered values do not match."
msgstr ""

#: venv/lib/python3.8/site-packages/click/termui.py:245
msgid "Error: invalid input"
msgstr ""

#: venv/lib/python3.8/site-packages/click/termui.py:776
msgid "Press any key to continue..."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:265
#, python-brace-format
msgid ""
"Choose from:\n"
"\t{choices}"
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:297
msgid "{value!r} is not {choice}."
msgid_plural "{value!r} is not one of {choices}."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/click/types.py:387
msgid "{value!r} does not match the format {format}."
msgid_plural "{value!r} does not match the formats {formats}."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/click/types.py:409
msgid "{value!r} is not a valid {number_type}."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:465
#, python-brace-format
msgid "{value} is not in the range {range}."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:606
msgid "{value!r} is not a valid boolean."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:630
msgid "{value!r} is not a valid UUID."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:811
msgid "file"
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:813
msgid "directory"
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:815
msgid "path"
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:861
msgid "{name} {filename!r} does not exist."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:870
msgid "{name} {filename!r} is a file."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:878
#, python-brace-format
msgid "{name} '{filename}' is a directory."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:887
msgid "{name} {filename!r} is not readable."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:896
msgid "{name} {filename!r} is not writable."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:905
msgid "{name} {filename!r} is not executable."
msgstr ""

#: venv/lib/python3.8/site-packages/click/types.py:972
#, python-brace-format
msgid "{len_type} values are required, but {len_value} was given."
msgid_plural "{len_type} values are required, but {len_value} were given."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/contrib/messages/apps.py:15
msgid "Messages"
msgstr ""

#: venv/lib/python3.8/site-packages/django/contrib/sitemaps/apps.py:8
msgid "Site Maps"
msgstr ""

#: venv/lib/python3.8/site-packages/django/contrib/staticfiles/apps.py:9
msgid "Static Files"
msgstr ""

#: venv/lib/python3.8/site-packages/django/contrib/syndication/apps.py:7
msgid "Syndication"
msgstr ""

#. Translators: String used to replace omitted page numbers in elided page
#. range generated by paginators, e.g. [1, 2, '…', 5, 6, 7, '…', 9, 10].
#: venv/lib/python3.8/site-packages/django/core/paginator.py:30
msgid "…"
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/paginator.py:50
msgid "That page number is not an integer"
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/paginator.py:52
msgid "That page number is less than 1"
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/paginator.py:57
msgid "That page contains no results"
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:22
msgid "Enter a valid value."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:104
#: venv/lib/python3.8/site-packages/django/forms/fields.py:751
msgid "Enter a valid URL."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:164
msgid "Enter a valid integer."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:175
msgid "Enter a valid email address."
msgstr ""

#. Translators: "letters" means latin letters: a-z and A-Z.
#: venv/lib/python3.8/site-packages/django/core/validators.py:256
msgid ""
"Enter a valid “slug” consisting of letters, numbers, underscores or hyphens."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:264
msgid ""
"Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or "
"hyphens."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:276
#: venv/lib/python3.8/site-packages/django/core/validators.py:284
#: venv/lib/python3.8/site-packages/django/core/validators.py:313
msgid "Enter a valid IPv4 address."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:293
#: venv/lib/python3.8/site-packages/django/core/validators.py:314
msgid "Enter a valid IPv6 address."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:305
#: venv/lib/python3.8/site-packages/django/core/validators.py:312
msgid "Enter a valid IPv4 or IPv6 address."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:348
msgid "Enter only digits separated by commas."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:354
#, python-format
msgid "Ensure this value is %(limit_value)s (it is %(show_value)s)."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:389
#, python-format
msgid "Ensure this value is less than or equal to %(limit_value)s."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:398
#, python-format
msgid "Ensure this value is greater than or equal to %(limit_value)s."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:407
#, python-format
msgid "Ensure this value is a multiple of step size %(limit_value)s."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:417
#, python-format
msgid ""
"Ensure this value has at least %(limit_value)d character (it has "
"%(show_value)d)."
msgid_plural ""
"Ensure this value has at least %(limit_value)d characters (it has "
"%(show_value)d)."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:435
#, python-format
msgid ""
"Ensure this value has at most %(limit_value)d character (it has "
"%(show_value)d)."
msgid_plural ""
"Ensure this value has at most %(limit_value)d characters (it has "
"%(show_value)d)."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:458
#: venv/lib/python3.8/site-packages/django/forms/fields.py:347
#: venv/lib/python3.8/site-packages/django/forms/fields.py:386
msgid "Enter a number."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:460
#, python-format
msgid "Ensure that there are no more than %(max)s digit in total."
msgid_plural "Ensure that there are no more than %(max)s digits in total."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:465
#, python-format
msgid "Ensure that there are no more than %(max)s decimal place."
msgid_plural "Ensure that there are no more than %(max)s decimal places."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:470
#, python-format
msgid ""
"Ensure that there are no more than %(max)s digit before the decimal point."
msgid_plural ""
"Ensure that there are no more than %(max)s digits before the decimal point."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:539
#, python-format
msgid ""
"File extension “%(extension)s” is not allowed. Allowed extensions are: "
"%(allowed_extensions)s."
msgstr ""

#: venv/lib/python3.8/site-packages/django/core/validators.py:600
msgid "Null characters are not allowed."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/base.py:1401
#: venv/lib/python3.8/site-packages/django/forms/models.py:899
msgid "and"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/base.py:1403
#, python-format
msgid "%(model_name)s with this %(field_labels)s already exists."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/constraints.py:17
#, python-format
msgid "Constraint “%(name)s” is violated."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:129
#, python-format
msgid "Value %(value)r is not a valid choice."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:130
msgid "This field cannot be null."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:131
msgid "This field cannot be blank."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:132
#, python-format
msgid "%(model_name)s with this %(field_label)s already exists."
msgstr ""

#. Translators: The 'lookup_type' is one of 'date', 'year' or
#. 'month'. Eg: "Title must be unique for pub_date year"
#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:136
#, python-format
msgid ""
"%(field_label)s must be unique for %(date_field_label)s %(lookup_type)s."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:174
#, python-format
msgid "Field of type: %(field_type)s"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1065
#, python-format
msgid "“%(value)s” value must be either True or False."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1066
#, python-format
msgid "“%(value)s” value must be either True, False, or None."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1068
msgid "Boolean (Either True or False)"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1118
#, python-format
msgid "String (up to %(max_length)s)"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1222
msgid "Comma-separated integers"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1323
#, python-format
msgid ""
"“%(value)s” value has an invalid date format. It must be in YYYY-MM-DD "
"format."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1327
#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1462
#, python-format
msgid ""
"“%(value)s” value has the correct format (YYYY-MM-DD) but it is an invalid "
"date."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1331
msgid "Date (without time)"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1458
#, python-format
msgid ""
"“%(value)s” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[."
"uuuuuu]][TZ] format."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1466
#, python-format
msgid ""
"“%(value)s” value has the correct format (YYYY-MM-DD HH:MM[:ss[.uuuuuu]]"
"[TZ]) but it is an invalid date/time."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1471
msgid "Date (with time)"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1595
#, python-format
msgid "“%(value)s” value must be a decimal number."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1597
msgid "Decimal number"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1754
#, python-format
msgid ""
"“%(value)s” value has an invalid format. It must be in [DD] [[HH:]MM:]ss[."
"uuuuuu] format."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1758
msgid "Duration"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1810
msgid "Email address"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1835
msgid "File path"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1913
#, python-format
msgid "“%(value)s” value must be a float."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1915
msgid "Floating point number"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1955
#, python-format
msgid "“%(value)s” value must be an integer."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1957
msgid "Integer"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2049
msgid "Big (8 byte) integer"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2066
msgid "Small integer"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2074
msgid "IPv4 address"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2105
msgid "IP address"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2198
#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2199
#, python-format
msgid "“%(value)s” value must be either None, True or False."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2201
msgid "Boolean (Either True, False or None)"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2252
msgid "Positive big integer"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2267
msgid "Positive integer"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2282
msgid "Positive small integer"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2298
#, python-format
msgid "Slug (up to %(max_length)s)"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2334
msgid "Text"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2409
#, python-format
msgid ""
"“%(value)s” value has an invalid format. It must be in HH:MM[:ss[.uuuuuu]] "
"format."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2413
#, python-format
msgid ""
"“%(value)s” value has the correct format (HH:MM[:ss[.uuuuuu]]) but it is an "
"invalid time."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2417
msgid "Time"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2525
msgid "URL"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2549
msgid "Raw binary data"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2614
#, python-format
msgid "“%(value)s” is not a valid UUID."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py:2616
msgid "Universally unique identifier"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/files.py:232
msgid "File"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/files.py:392
msgid "Image"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/json.py:18
msgid "A JSON object"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/json.py:20
msgid "Value must be valid JSON."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/related.py:920
#, python-format
msgid "%(model)s instance with %(field)s %(value)r does not exist."
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/related.py:922
msgid "Foreign Key (type determined by related field)"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/related.py:1229
msgid "One-to-one relationship"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/related.py:1286
#, python-format
msgid "%(from)s-%(to)s relationship"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/related.py:1288
#, python-format
msgid "%(from)s-%(to)s relationships"
msgstr ""

#: venv/lib/python3.8/site-packages/django/db/models/fields/related.py:1336
msgid "Many-to-many relationship"
msgstr ""

#. Translators: If found as last label character, these punctuation
#. characters will prevent the default label_suffix to be appended to the label
#: venv/lib/python3.8/site-packages/django/forms/boundfield.py:176
msgid ":?.!"
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:91
msgid "This field is required."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:298
msgid "Enter a whole number."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:467
#: venv/lib/python3.8/site-packages/django/forms/fields.py:1240
msgid "Enter a valid date."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:490
#: venv/lib/python3.8/site-packages/django/forms/fields.py:1241
msgid "Enter a valid time."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:517
msgid "Enter a valid date/time."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:551
msgid "Enter a valid duration."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:552
#, python-brace-format
msgid "The number of days must be between {min_days} and {max_days}."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:618
msgid "No file was submitted. Check the encoding type on the form."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:619
msgid "No file was submitted."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:620
msgid "The submitted file is empty."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:622
#, python-format
msgid "Ensure this filename has at most %(max)d character (it has %(length)d)."
msgid_plural ""
"Ensure this filename has at most %(max)d characters (it has %(length)d)."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:627
msgid "Please either submit a file or check the clear checkbox, not both."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:693
msgid ""
"Upload a valid image. The file you uploaded was either not an image or a "
"corrupted image."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:856
#: venv/lib/python3.8/site-packages/django/forms/fields.py:948
#: venv/lib/python3.8/site-packages/django/forms/models.py:1572
#, python-format
msgid "Select a valid choice. %(value)s is not one of the available choices."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:950
#: venv/lib/python3.8/site-packages/django/forms/fields.py:1069
#: venv/lib/python3.8/site-packages/django/forms/models.py:1570
msgid "Enter a list of values."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:1070
msgid "Enter a complete value."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:1309
msgid "Enter a valid UUID."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/fields.py:1339
msgid "Enter a valid JSON."
msgstr ""

#. Translators: This is the default suffix added to form field labels
#: venv/lib/python3.8/site-packages/django/forms/forms.py:98
msgid ":"
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/forms.py:248
#: venv/lib/python3.8/site-packages/django/forms/forms.py:332
#, python-format
msgid "(Hidden field %(name)s) %(error)s"
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/formsets.py:63
#, python-format
msgid ""
"ManagementForm data is missing or has been tampered with. Missing fields: "
"%(field_names)s. You may need to file a bug report if the issue persists."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/formsets.py:67
#, python-format
msgid "Please submit at most %(num)d form."
msgid_plural "Please submit at most %(num)d forms."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/forms/formsets.py:72
#, python-format
msgid "Please submit at least %(num)d form."
msgid_plural "Please submit at least %(num)d forms."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/forms/formsets.py:483
#: venv/lib/python3.8/site-packages/django/forms/formsets.py:490
msgid "Order"
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/formsets.py:496
msgid "Delete"
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/models.py:892
#, python-format
msgid "Please correct the duplicate data for %(field)s."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/models.py:897
#, python-format
msgid "Please correct the duplicate data for %(field)s, which must be unique."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/models.py:904
#, python-format
msgid ""
"Please correct the duplicate data for %(field_name)s which must be unique "
"for the %(lookup)s in %(date_field)s."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/models.py:913
msgid "Please correct the duplicate values below."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/models.py:1344
msgid "The inline value did not match the parent instance."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/models.py:1435
msgid "Select a valid choice. That choice is not one of the available choices."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/models.py:1574
#, python-format
msgid "“%(pk)s” is not a valid value."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/utils.py:226
#, python-format
msgid ""
"%(datetime)s couldn’t be interpreted in time zone %(current_timezone)s; it "
"may be ambiguous or it may not exist."
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/widgets.py:439
msgid "Clear"
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/widgets.py:440
msgid "Currently"
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/widgets.py:441
msgid "Change"
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/widgets.py:770
msgid "Unknown"
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/widgets.py:771
msgid "Yes"
msgstr ""

#: venv/lib/python3.8/site-packages/django/forms/widgets.py:772
msgid "No"
msgstr ""

#. Translators: Please do not add spaces around commas.
#: venv/lib/python3.8/site-packages/django/template/defaultfilters.py:853
msgid "yes,no,maybe"
msgstr ""

#: venv/lib/python3.8/site-packages/django/template/defaultfilters.py:883
#: venv/lib/python3.8/site-packages/django/template/defaultfilters.py:900
#, python-format
msgid "%(size)d byte"
msgid_plural "%(size)d bytes"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/template/defaultfilters.py:902
#, python-format
msgid "%s KB"
msgstr ""

#: venv/lib/python3.8/site-packages/django/template/defaultfilters.py:904
#, python-format
msgid "%s MB"
msgstr ""

#: venv/lib/python3.8/site-packages/django/template/defaultfilters.py:906
#, python-format
msgid "%s GB"
msgstr ""

#: venv/lib/python3.8/site-packages/django/template/defaultfilters.py:908
#, python-format
msgid "%s TB"
msgstr ""

#: venv/lib/python3.8/site-packages/django/template/defaultfilters.py:910
#, python-format
msgid "%s PB"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dateformat.py:77
msgid "p.m."
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dateformat.py:78
msgid "a.m."
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dateformat.py:83
msgid "PM"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dateformat.py:84
msgid "AM"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dateformat.py:155
msgid "midnight"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dateformat.py:157
msgid "noon"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:7
msgid "Monday"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:8
msgid "Tuesday"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:9
msgid "Wednesday"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:10
msgid "Thursday"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:11
msgid "Friday"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:12
msgid "Saturday"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:13
msgid "Sunday"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:16
msgid "Mon"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:17
msgid "Tue"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:18
msgid "Wed"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:19
msgid "Thu"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:20
msgid "Fri"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:21
msgid "Sat"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:22
msgid "Sun"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:25
msgid "January"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:26
msgid "February"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:27
msgid "March"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:28
msgid "April"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:29
msgid "May"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:30
msgid "June"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:31
msgid "July"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:32
msgid "August"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:33
msgid "September"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:34
msgid "October"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:35
msgid "November"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:36
msgid "December"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:39
msgid "jan"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:40
msgid "feb"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:41
msgid "mar"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:42
msgid "apr"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:43
msgid "may"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:44
msgid "jun"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:45
msgid "jul"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:46
msgid "aug"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:47
msgid "sep"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:48
msgid "oct"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:49
msgid "nov"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:50
msgid "dec"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:53
msgctxt "abbrev. month"
msgid "Jan."
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:54
msgctxt "abbrev. month"
msgid "Feb."
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:55
msgctxt "abbrev. month"
msgid "March"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:56
msgctxt "abbrev. month"
msgid "April"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:57
msgctxt "abbrev. month"
msgid "May"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:58
msgctxt "abbrev. month"
msgid "June"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:59
msgctxt "abbrev. month"
msgid "July"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:60
msgctxt "abbrev. month"
msgid "Aug."
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:61
msgctxt "abbrev. month"
msgid "Sept."
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:62
msgctxt "abbrev. month"
msgid "Oct."
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:63
msgctxt "abbrev. month"
msgid "Nov."
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:64
msgctxt "abbrev. month"
msgid "Dec."
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:67
msgctxt "alt. month"
msgid "January"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:68
msgctxt "alt. month"
msgid "February"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:69
msgctxt "alt. month"
msgid "March"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:70
msgctxt "alt. month"
msgid "April"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:71
msgctxt "alt. month"
msgid "May"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:72
msgctxt "alt. month"
msgid "June"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:73
msgctxt "alt. month"
msgid "July"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:74
msgctxt "alt. month"
msgid "August"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:75
msgctxt "alt. month"
msgid "September"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:76
msgctxt "alt. month"
msgid "October"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:77
msgctxt "alt. month"
msgid "November"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/dates.py:78
msgctxt "alt. month"
msgid "December"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/ipv6.py:8
msgid "This is not a valid IPv6 address."
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/text.py:76
#, python-format
msgctxt "String to return when truncating text"
msgid "%(truncated_text)s…"
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/text.py:252
msgid "or"
msgstr ""

#. Translators: This string is used as a separator between list elements
#: venv/lib/python3.8/site-packages/django/utils/text.py:271
#: venv/lib/python3.8/site-packages/django/utils/timesince.py:94
msgid ", "
msgstr ""

#: venv/lib/python3.8/site-packages/django/utils/timesince.py:9
#, python-format
msgid "%(num)d year"
msgid_plural "%(num)d years"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/utils/timesince.py:10
#, python-format
msgid "%(num)d month"
msgid_plural "%(num)d months"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/utils/timesince.py:11
#, python-format
msgid "%(num)d week"
msgid_plural "%(num)d weeks"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/utils/timesince.py:12
#, python-format
msgid "%(num)d day"
msgid_plural "%(num)d days"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/utils/timesince.py:13
#, python-format
msgid "%(num)d hour"
msgid_plural "%(num)d hours"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/utils/timesince.py:14
#, python-format
msgid "%(num)d minute"
msgid_plural "%(num)d minutes"
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.8/site-packages/django/views/csrf.py:111
msgid "Forbidden"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/csrf.py:112
msgid "CSRF verification failed. Request aborted."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/csrf.py:116
msgid ""
"You are seeing this message because this HTTPS site requires a “Referer "
"header” to be sent by your web browser, but none was sent. This header is "
"required for security reasons, to ensure that your browser is not being "
"hijacked by third parties."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/csrf.py:122
msgid ""
"If you have configured your browser to disable “Referer” headers, please re-"
"enable them, at least for this site, or for HTTPS connections, or for “same-"
"origin” requests."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/csrf.py:127
msgid ""
"If you are using the <meta name=\"referrer\" content=\"no-referrer\"> tag or "
"including the “Referrer-Policy: no-referrer” header, please remove them. The "
"CSRF protection requires the “Referer” header to do strict referer checking. "
"If you’re concerned about privacy, use alternatives like <a rel=\"noreferrer"
"\" …> for links to third-party sites."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/csrf.py:136
msgid ""
"You are seeing this message because this site requires a CSRF cookie when "
"submitting forms. This cookie is required for security reasons, to ensure "
"that your browser is not being hijacked by third parties."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/csrf.py:142
msgid ""
"If you have configured your browser to disable cookies, please re-enable "
"them, at least for this site, or for “same-origin” requests."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/csrf.py:148
msgid "More information is available with DEBUG=True."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:44
msgid "No year specified"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:64
#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:115
#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:214
msgid "Date out of range"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:94
msgid "No month specified"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:147
msgid "No day specified"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:194
msgid "No week specified"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:349
#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:380
#, python-format
msgid "No %(verbose_name_plural)s available"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:652
#, python-format
msgid ""
"Future %(verbose_name_plural)s not available because %(class_name)s."
"allow_future is False."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/dates.py:692
#, python-format
msgid "Invalid date string “%(datestr)s” given format “%(format)s”"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/detail.py:56
#, python-format
msgid "No %(verbose_name)s found matching the query"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/list.py:70
msgid "Page is not “last”, nor can it be converted to an int."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/list.py:77
#, python-format
msgid "Invalid page (%(page_number)s): %(message)s"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/generic/list.py:169
#, python-format
msgid "Empty list and “%(class_name)s.allow_empty” is False."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/static.py:38
msgid "Directory indexes are not allowed here."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/static.py:40
#, python-format
msgid "“%(path)s” does not exist"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/static.py:79
#, python-format
msgid "Index of %(directory)s"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/templates/default_urlconf.html:7
#: venv/lib/python3.8/site-packages/django/views/templates/default_urlconf.html:221
msgid "The install worked successfully! Congratulations!"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/templates/default_urlconf.html:207
#, python-format
msgid ""
"View <a href=\"https://docs.djangoproject.com/en/%(version)s/releases/\" "
"target=\"_blank\" rel=\"noopener\">release notes</a> for Django %(version)s"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/templates/default_urlconf.html:222
#, python-format
msgid ""
"You are seeing this page because <a href=\"https://docs.djangoproject.com/en/"
"%(version)s/ref/settings/#debug\" target=\"_blank\" rel=\"noopener"
"\">DEBUG=True</a> is in your settings file and you have not configured any "
"URLs."
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/templates/default_urlconf.html:230
msgid "Django Documentation"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/templates/default_urlconf.html:231
msgid "Topics, references, &amp; how-to’s"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/templates/default_urlconf.html:239
msgid "Tutorial: A Polling App"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/templates/default_urlconf.html:240
msgid "Get started with Django"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/templates/default_urlconf.html:248
msgid "Django Community"
msgstr ""

#: venv/lib/python3.8/site-packages/django/views/templates/default_urlconf.html:249
msgid "Connect, get help, or contribute"
msgstr ""

#: warehouse/article/views.py:30 warehouse/article/views.py:55
msgid "Article not found"
msgstr "Articolo non trovato"

#: warehouse/article/views.py:35
msgid "Article already exists"
msgstr "Articolo già presente"

#: warehouse/article/views.py:80
msgid "Unable to print label. Article not found"
msgstr "Impossibile stampare etichetta. L'articolo selezionato non esiste"

#: warehouse/article/views.py:97
msgid "Articles with no availability"
msgstr "Articoli a giacenza zero"

#: warehouse/article/views.py:100
msgid "Articles with availability below reorder threshold"
msgstr "Articoli sotto soglia riordino"

#: warehouse/inventory/views.py:28
msgid "Inventory cycle not created"
msgstr "Valorizzazione magazzino virtuale non creata"

#: warehouse/inventory/views.py:30
msgid "Inventory cycle created succesfully"
msgstr "Valorizzazione magazzino virtuale creata con successo"

#: warehouse/transaction/views.py:29
msgid "Transaction details not found"
msgstr "Dettagli movimentazione non trovati"

#: warehouse/transaction/views.py:50
msgid "Transaction created successfully"
msgstr "Movimentazione creata con successo"

#: warehouse/transaction/views.py:53
msgid "Error while parsing transaction"
msgstr "Errore durante l'elaborazione della movimentazione"

#: warehouse/transaction/views.py:57
msgid "Some items do have an inconsistent quantity. Transaction not created"
msgstr ""
"Alcuni articoli hanno una quantità non consistente. Movimentazione non "
"registrata"

#: warehouse/transaction/views.py:60
msgid "Error while processing transaction"
msgstr "Errore durante l'elaborazione della movimentazione"
